### PR TITLE
add victory threshold option

### PR DESCRIPTION
**Pull request by wtadler**
threshold defaults to 50%. script checks to make sure that the entered value is a number greater than 0 and less than 100.

also corrected a few typos.

### CODE REVIEW

**Comment by PeterTheOne** [comment]
Thanks for contributing, I made some minor changes. :)

**Comment by wtadler** [comment]
Your changes look nice!

An organization I work with has bylaws that require a 2/3 victory threshold, but there was no good online tool for running such an election. I had no experience with JS, but this looked like a relatively simple update. This was a good first JS project for me—thanks!

**Comment by PeterTheOne** [comment]
Can you name the organization?

**Comment by wtadler** [comment]
[New Kings Democrats](http://www.newkingsdemocrats.com/about), a volunteer group trying to bring change and transparency to the Democratic party in Brooklyn, NY. And you can see the voting procedure in the [bylaws](http://www.newkingsdemocrats.com/bylaws), section VI.B.2

**Pull request merged**
